import { Section } from '../Section';
import {
  BlockWrap,
  Color,
  Img,
  Svg,
  TextAbout,
  TextItem,
  Title,
} from './About.styled';
import sprite from '../../assets/images/sprite.svg';
import ape_mob from '../../assets/images/ape_mob.png';

export const About = () => {
  return (
    <Section>
      <Title>
        a Story that started with{' '}
        <Color>
          one simple <br />
          ape
        </Color>
      </Title>
      <TextAbout>
        WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
        IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </TextAbout>

      <BlockWrap>
        <Svg>
          <use href={`${sprite}#cross`}></use>
        </Svg>
        <TextItem>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </TextItem>
      </BlockWrap>
      <Img src={ape_mob} alt="ape" />
    </Section>
  );
};
