import { Section } from '../Section';
import {
  BlockWrap,
  Color,
  Img,
  Svg,
  TextAbout,
  TextItem,
  Title,
  WrapTitle,
} from './About.styled';
import sprite from '../../assets/images/sprite.svg';
import ape_mob from '../../assets/images/ape_mob.png';
import ape_tab from '../../assets/images/ape_tab.png';
import ape_des from '../../assets/images/ape_des.png';

export const About = ({ width }) => {
  return (
    <Section>
      <WrapTitle>
        <Title>
          a Story that started with{' '}
          <Color>
            one simple&nbsp;
            {width < 768 && <br />}
            ape
          </Color>
        </Title>
        <TextAbout>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE
          {width > 768 && <br />}
          &nbsp;YACHT
        </TextAbout>
      </WrapTitle>

      <BlockWrap>
        <Svg>
          <use href={`${sprite}#cross`}></use>
        </Svg>
        <TextItem>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </TextItem>
      </BlockWrap>
      {/* <Img src={ape_mob} alt="ape" /> */}
      {width < 768 && <Img src={ape_mob} alt="ape" />}
      {width > 768 && width < 1280 && <Img src={ape_tab} alt="ape" />}
      {width > 1280 && <Img src={ape_des} alt="ape" />}
    </Section>
  );
};
